export const LOAD_USER="LOAD_USER"
export const LOGIN="LOGIN"
export const REGISTER="REGISTER"
export const FAIL_USER="FAIL_USER"
export const CURRENT="CURRENT"
export const LOGOUT="LOGOUT"
export const CLEARERROR="CLEARERROR"


/////
export const ADDPROFILE ="ADDPROFILE"
export const FAIL_PROFILE="FAIL_PROFILE"
export const LOADPROFILE="LOADPROFILE"
export const GETPROFILE="GETPROFILE"
export const EDITPROFILE="EDITPROFILE"
////
export const LOADCLASSES="LOADCLASSES"
export const FAIL_CLASSES="FAIL_CLASSES"
export const GETCLASSES="GETCLASSES"
export const GETCLASSE="GETCLASSE"
export const LOADCLASSE="LOADCLASSE"
///
export const LOADPUPILS="LOADPUPILS"
export const LOADPUPIL="LOADPUPIL"
export const GETPUPILS="GETPUPILS"
export const FAIL_PUPILS="FAIL_PUPILS"

///
export const TOOGLETRUE="TOOGLETRUE"
export const TOOGLEFALSE="TOOGLEFALSE"
